spring.application.name=smart-resume-parser

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smart_resume_parser}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.region=${AWS_REGION}

spring.ai.openai.api-key=${OPENAI_API_KEY}


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=2MB

app.upload.allowed-content-types=image/png,image/jpeg,application/pdf,image/tiff
app.upload.allowed-extensions=.png,.jpg,.jpeg,.pdf,.tiff

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true  
server.error.include-message=always
spring.jpa.open-in-view=false